### ISSUE TITLE
Unique edits in both master and develop?

### ISSUE THREAD

**Issue by patcon** [fnichol/chef-jenkins#20]
Hey Fletcher,

It seems that master has new pull requests brought in, but develop has the edits for using the mirrors url and all that. Was that just an oversight?

And hey, let me know if you need help maintaining -- I know that sometimes shit just gets busy, and I'm happy to chip in

**Comment by fnichol** [comment]
# Jenkins Chef Cookbook Has Moved

Hi there.

First off, I'm sorry the reply may come extremely late (and may not even apply to anyone on this thread anymore), but I wanted to let everyone know that the current canonical source for the Jenkins Chef cookbook is maintained by [Chef Software Inc.](https://chef.io) here:

* Source code: https://github.com/chef-cookbooks/jenkins
* Supermarket: https://supermarket.chef.io/cookbooks/jenkins

Since this has been the case for over 2 years, I'm trying to redirect any interest and traffic there, and slowing this repository to a "redirection state". As a consequence, I'm going to close this issue out. The master branch has been left intact for the time being, but it is highly recommended to no longer link against this repository in the future.

Please direct any development, issues, and pull requests at the above GitHub repository. Thank you very much!
