### ISSUE TITLE
Check out Jenkins.rb rubygem?

### ISSUE THREAD

**Issue by patcon** [fnichol/chef-jenkins#21]
https://github.com/cowboyd/jenkins.rb

Not sure if this is a good idea of a bad idea... Thinking more for communicating with it through its API, and perhaps not the anything like setup, but just thought I'd toss it out there. Just perhaps something to watch more than anything else :)

**Comment by fnichol** [comment]
# Jenkins Chef Cookbook Has Moved

Hi there.

First off, I'm sorry the reply may come extremely late (and may not even apply to anyone on this thread anymore), but I wanted to let everyone know that the current canonical source for the Jenkins Chef cookbook is maintained by [Chef Software Inc.](https://chef.io) here:

* Source code: https://github.com/chef-cookbooks/jenkins
* Supermarket: https://supermarket.chef.io/cookbooks/jenkins

Since this has been the case for over 2 years, I'm trying to redirect any interest and traffic there, and slowing this repository to a "redirection state". As a consequence, I'm going to close this issue out. The master branch has been left intact for the time being, but it is highly recommended to no longer link against this repository in the future.

Please direct any development, issues, and pull requests at the above GitHub repository. Thank you very much!
