### ISSUE TITLE
jenkins::ssh_node recipe failing on execution of node_info.groovy

### ISSUE THREAD

**Issue by timclemons** [fnichol/chef-jenkins#23]
On attempting to add a ssh node to a Jenkins 1.461 server, I'm encountering several problems with the execution of the node_info.groovy script.  On manually editing the file, I've discovered the following gets it operational again:

* Enclosing '#' comments with /* */.
* Replacing 'jenkins' with 'hudson' on the import lines.
* Replacing 'Jenkins' with 'Hudson' on the line 'slave = Jenkins.instance.getNode(this.args[0]) as Slave'

On checking the Jenkins 1.461 page, I see that this appears to be the latest release.  Any ideas why the node_info script would be failing for me?

**Comment by fnichol** [comment]
# Jenkins Chef Cookbook Has Moved

Hi there.

First off, I'm sorry the reply may come extremely late (and may not even apply to anyone on this thread anymore), but I wanted to let everyone know that the current canonical source for the Jenkins Chef cookbook is maintained by [Chef Software Inc.](https://chef.io) here:

* Source code: https://github.com/chef-cookbooks/jenkins
* Supermarket: https://supermarket.chef.io/cookbooks/jenkins

Since this has been the case for over 2 years, I'm trying to redirect any interest and traffic there, and slowing this repository to a "redirection state". As a consequence, I'm going to close this issue out. The master branch has been left intact for the time being, but it is highly recommended to no longer link against this repository in the future.

Please direct any development, issues, and pull requests at the above GitHub repository. Thank you very much!
