### ISSUE TITLE
Download *.jpi files instead of *.hpi

### ISSUE THREAD

**Issue by JeffBellegarde** [fnichol/chef-jenkins#25]
While experimenting with plugins I can install them manually via jenkins which downloads a .jpi file and expands it.  When the plugin is then added to to chef's plugin list chef then downloads a .hpi file and expands it.  However, the .jpi file still exists.

Once the plugin is update to a new version we start running into problems. It looks likes Jenkins is running on a combination of the two versions leading to ClassNotFound errors due to version discrepancies between the .jpi and .hpi files.

I think that downloading .jpi files instead of .hpi files would avoid the problem entirely.

**Comment by fnichol** [comment]
# Jenkins Chef Cookbook Has Moved

Hi there.

First off, I'm sorry the reply may come extremely late (and may not even apply to anyone on this thread anymore), but I wanted to let everyone know that the current canonical source for the Jenkins Chef cookbook is maintained by [Chef Software Inc.](https://chef.io) here:

* Source code: https://github.com/chef-cookbooks/jenkins
* Supermarket: https://supermarket.chef.io/cookbooks/jenkins

Since this has been the case for over 2 years, I'm trying to redirect any interest and traffic there, and slowing this repository to a "redirection state". As a consequence, I'm going to close this issue out. The master branch has been left intact for the time being, but it is highly recommended to no longer link against this repository in the future.

Please direct any development, issues, and pull requests at the above GitHub repository. Thank you very much!
