### ISSUE TITLE
Not installing latest package on ubuntu

### ISSUE THREAD

**Issue by jondot** [fnichol/chef-jenkins#26]
Looks like this was fixed on this fork

https://github.com/gumayunov/chef-jenkins/commit/0494ab55fd9253858226f63c6a9994c907bb15b9

**Comment by fnichol** [comment]
# Jenkins Chef Cookbook Has Moved

Hi there.

First off, I'm sorry the reply may come extremely late (and may not even apply to anyone on this thread anymore), but I wanted to let everyone know that the current canonical source for the Jenkins Chef cookbook is maintained by [Chef Software Inc.](https://chef.io) here:

* Source code: https://github.com/chef-cookbooks/jenkins
* Supermarket: https://supermarket.chef.io/cookbooks/jenkins

Since this has been the case for over 2 years, I'm trying to redirect any interest and traffic there, and slowing this repository to a "redirection state". As a consequence, I'm going to close this issue out. The master branch has been left intact for the time being, but it is highly recommended to no longer link against this repository in the future.

Please direct any development, issues, and pull requests at the above GitHub repository. Thank you very much!
