### ISSUE TITLE
Hangs on Ubuntu after install during config; works on CentOS

### ISSUE THREAD

**Issue by celeduc** [fnichol/chef-jenkins#27]
I tried both x64 and i386, and both of them hang while doing post-installation configuration of Jenkins.  I'm not sure what it's hung up on, and not sure where to look.

 3327 ?        S      0:00 apt-get -q -y install jenkins=1.481
 3520 ?        S      0:00 /usr/bin/dpkg --status-fd 76 --configure daemon jenkins
 3523 ?        S      0:00 /bin/sh /var/lib/dpkg/info/jenkins.postinst configure 

/var/log/install:
I, [2012-09-14T07:39:41.760781 #980]  INFO -- : 07:39:41: Setting up jenkins (1.481) ...
I, [2012-09-14T07:39:41.760840 #980]  INFO -- : 07:39:41: * Starting Jenkins Continuous Integration Server jenkins
I, [2012-09-14T07:39:41.774541 #980]  INFO -- : SEND b1 [push v15] (999 bytes) <70399240001:7be735a0dc52a58d105b2422aac9bbf6> /auditor/update_entry, persistent 

/var/log/apt/history.log: 
Start-Date: 2012-09-14  07:39:39
Install: jenkins (1.481), daemon (0.6.3-1)

/var/log/jenkins/jenkins.log:
INFO: Started SSHD at port 60256
Sep 14, 2012 7:39:54 AM jenkins.InitReactorRunner$1 onAttained
INFO: Completed initialization
Sep 14, 2012 7:39:54 AM hudson.TcpSlaveAgentListener <init>
INFO: JNLP slave agent listener started on TCP port 33826
Sep 14, 2012 7:39:54 AM hudson.WebAppMain$2 run
INFO: Jenkins is fully up and running

/var/log/dpkg.log:
2012-09-14 07:39:41 configure jenkins 1.481 1.481
2012-09-14 07:39:41 status unpacked jenkins 1.481
2012-09-14 07:39:41 status unpacked jenkins 1.481
2012-09-14 07:39:41 status unpacked jenkins 1.481
2012-09-14 07:39:41 status unpacked jenkins 1.481
2012-09-14 07:39:41 status half-configured jenkins 1.481

/var/log/user.log:
07:39:41: Setting up jenkins (1.481) ...
Sep 14 07:39:41 ip-10-245-74-63 RightLink[980]: 07:39:41: * Starting Jenkins Continuous Integration Server jenkins
Sep 14 07:39:41 ip-10-245-74-63 RightLink[980]: SEND b1 [push v15] (999 bytes) <70399240001:7be735a0dc52a58d105b2422aac9bbf6> /auditor/update_entry, persistent

**Comment by fnichol** [comment]
# Jenkins Chef Cookbook Has Moved

Hi there.

First off, I'm sorry the reply may come extremely late (and may not even apply to anyone on this thread anymore), but I wanted to let everyone know that the current canonical source for the Jenkins Chef cookbook is maintained by [Chef Software Inc.](https://chef.io) here:

* Source code: https://github.com/chef-cookbooks/jenkins
* Supermarket: https://supermarket.chef.io/cookbooks/jenkins

Since this has been the case for over 2 years, I'm trying to redirect any interest and traffic there, and slowing this repository to a "redirection state". As a consequence, I'm going to close this issue out. The master branch has been left intact for the time being, but it is highly recommended to no longer link against this repository in the future.

Please direct any development, issues, and pull requests at the above GitHub repository. Thank you very much!
