### ISSUE TITLE
Unable to install jenkins from Debian package (v 1.485)

### ISSUE THREAD

**Issue by sameersegal** [fnichol/chef-jenkins#28]
Hi,

Until this afternoon I was able to install jenkins using the cookbook. Now I am getting a 404 error when it tries to run ``` Processing package[jenkins] action install ``` and get ``` apt-get -q -y install jenkins=1.485 returned 100, expected 0```

I tried specify a version but it is not able to install the package. 

I even SSH into the server and tried previous versions:
``` 
ubuntu@ip-10-134-215-196:~$ sudo apt-get install jenkins=1.484
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version '1.484' for 'jenkins' was not found
```

I guess this could be an issue with the debian repo?

Additionally, I wanted to know if there is a way to get specify a ```config.xml``` file for Jenkins server. I can create a template and copy it over but how do I do it in an idempotent way?

**Comment by fnichol** [comment]
# Jenkins Chef Cookbook Has Moved

Hi there.

First off, I'm sorry the reply may come extremely late (and may not even apply to anyone on this thread anymore), but I wanted to let everyone know that the current canonical source for the Jenkins Chef cookbook is maintained by [Chef Software Inc.](https://chef.io) here:

* Source code: https://github.com/chef-cookbooks/jenkins
* Supermarket: https://supermarket.chef.io/cookbooks/jenkins

Since this has been the case for over 2 years, I'm trying to redirect any interest and traffic there, and slowing this repository to a "redirection state". As a consequence, I'm going to close this issue out. The master branch has been left intact for the time being, but it is highly recommended to no longer link against this repository in the future.

Please direct any development, issues, and pull requests at the above GitHub repository. Thank you very much!
