### ISSUE TITLE
Ubuntu 10.04 install jenkins::default non-standard port

### ISSUE THREAD

**Issue by openfirmware** [fnichol/chef-jenkins#7]
Trying to install Jenkins with the jenkins::default recipe on Ubuntu 10.04.2 with another service already running on port 8080 causes the install the stall at the "block_until_operational" step. After interrupting out and uninstalling jenkins from apt, I set the node.jenkins.server.port to 18080, but this still had no effect.

Upon investigation, /etc/default/jenkins still had the port as 8080, which is directly from https://github.com/jenkinsci/jenkins/blob/master/debian/debian/jenkins.default. I bundled a modified copy of the defaults file that grabs the jenkins.server.port in the templates dir, and ran a template block (for debian/ubuntu only) near the top of the jenkins::default recipe. This works and successfully installs Jenkins.

**Comment by fnichol** [comment]
# Jenkins Chef Cookbook Has Moved

Hi there.

First off, I'm sorry the reply may come extremely late (and may not even apply to anyone on this thread anymore), but I wanted to let everyone know that the current canonical source for the Jenkins Chef cookbook is maintained by [Chef Software Inc.](https://chef.io) here:

* Source code: https://github.com/chef-cookbooks/jenkins
* Supermarket: https://supermarket.chef.io/cookbooks/jenkins

Since this has been the case for over 2 years, I'm trying to redirect any interest and traffic there, and slowing this repository to a "redirection state". As a consequence, I'm going to close this issue out. The master branch has been left intact for the time being, but it is highly recommended to no longer link against this repository in the future.

Please direct any development, issues, and pull requests at the above GitHub repository. Thank you very much!
