### ISSUE TITLE
chef-solo compatible node_ssh recipe

### ISSUE THREAD

**Issue by hedgehog** [fnichol/chef-jenkins#8]
Would be nice to create jenkins master and ssh nodes using chef-solo recipes. Currently these break due to relying on search. Intermediate, special use case, could be a `node_vagrant_ssh` recipe

**Comment by fnichol** [comment]
# Jenkins Chef Cookbook Has Moved

Hi there.

First off, I'm sorry the reply may come extremely late (and may not even apply to anyone on this thread anymore), but I wanted to let everyone know that the current canonical source for the Jenkins Chef cookbook is maintained by [Chef Software Inc.](https://chef.io) here:

* Source code: https://github.com/chef-cookbooks/jenkins
* Supermarket: https://supermarket.chef.io/cookbooks/jenkins

Since this has been the case for over 2 years, I'm trying to redirect any interest and traffic there, and slowing this repository to a "redirection state". As a consequence, I'm going to close this issue out. The master branch has been left intact for the time being, but it is highly recommended to no longer link against this repository in the future.

Please direct any development, issues, and pull requests at the above GitHub repository. Thank you very much!
