### ISSUE TITLE
update plugin center on install

### ISSUE THREAD

**Issue by hedgehog** [fnichol/chef-jenkins#9]
On installing a plugin you will encounter the following error.

    $ java -jar jenkins-cli.jar -s http://localhost:9000 install-plugin findbugs
    findbugs is neither a valid file, URL, nor a plugin artifact name in the update center
    No update center data is retrieved yet from: http://updates.jenkins-ci.org/update-center.json
    findbugs looks like a short plugin name. Did you mean 'null'?

The Jenkins issue is [here][1]
[Workaround/solution is here][0]

[0]: https://gist.github.com/1026918
[1]: https://issues.jenkins-ci.org/browse/JENKINS-10061

**Comment by fnichol** [comment]
# Jenkins Chef Cookbook Has Moved

Hi there.

First off, I'm sorry the reply may come extremely late (and may not even apply to anyone on this thread anymore), but I wanted to let everyone know that the current canonical source for the Jenkins Chef cookbook is maintained by [Chef Software Inc.](https://chef.io) here:

* Source code: https://github.com/chef-cookbooks/jenkins
* Supermarket: https://supermarket.chef.io/cookbooks/jenkins

Since this has been the case for over 2 years, I'm trying to redirect any interest and traffic there, and slowing this repository to a "redirection state". As a consequence, I'm going to close this issue out. The master branch has been left intact for the time being, but it is highly recommended to no longer link against this repository in the future.

Please direct any development, issues, and pull requests at the above GitHub repository. Thank you very much!
